### ISSUE TITLE
possible to pass search spec without implementing functioning search

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/partial-locals-lab#11]
The `student_index_spec.rb` file checks for the presence of a search method and rendering of a partial--but there isn't a check to see that the search is actually implemented as described by the README ("Second, they also want to add some search functionality so that a user can search for a student by name. It's okay if other students with similar names are returned in the search results.")  

It's possible to pass all specs for this lab without updating student#index in `student_controller.rb` to use the model's search method. i.e., leaving student#index defined as `@students = Student.all`.   When rendered in-browser, though, the search form doesn't actually work.  Not sure what test could be added...maybe one that visits students/index, fills the search form with a name, then checks that the last response does not include a name that wouldn't otherwise be returned?

**Comment by sgharms** [comment]
I've added a test on the student#index function that requires successful execution of a search. Thanks for your input!
