### ISSUE TITLE
Search functionality requirement is unclear

### ISSUE THREAD

**Issue by marielfrank** [learn-co-curriculum/partial-locals-lab#12]
The following lines make it seem as though we need to set up a form or somehow receive user input on the students/show or students/index pages. However, this is not necessary and so the instructions are really confusing regarding what specifically we need to do, or what the desired end result is:

> add some search functionality so that a user can search for a student by name. It's okay if other students with similar names are returned in the search results.
> Add in search functionality such that users can search for a student by name and see all matching results on the students index page. The results should be displayed by rendering a students/_student.html.erb partial.

**Comment by FionaDL** [comment]
Agreed.

**Comment by dwyn** [comment]
+1

**Comment by sgharms** [comment]
Update coming. Thanks!
