### ISSUE TITLE
Unable to pass variable @students from classroom controller 

### ISSUE THREAD

**Issue by KristenLeach** [learn-co-curriculum/partial-locals-lab#14]
For the classroom#show view using the student partial, I set up my classroom controller like so: 
def show
    @classroom = Classroom.find(params[:id])
    @students = @classroom.students
end 

I then iterated through @students and used each individual student in the student partial. While this works in my browser as expected, the tests failed and kept giving me an error that @students was nil. Testing it in pry and the console showed that @classroom.students gave me back a full list of students, and it showed all students in the browser. 

The only way I could pass the tests was to use @classroom.students.each to iterate on the show page rather than passing the @students variable I created in the controller. A technical coach helped me figure out the problem and suggested that it could be something specific in the tests that is not allowing the use of a variable @students.

**Comment by KristenLeach** [comment]
I'm not sure why this comment keeps capitalizing @students, but it was not capitalized in my program. :-)

**Comment by sgharms** [comment]
I think this may have been caused by using `collection:` to pass the collection. Our tests were too narrow and required an each-based solution. I think this issue is fixed but if you find it is not, please re-open and we'll pursue.
