### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by jljardon** [learn-co-curriculum/partial-locals-lab#15]
The "Faker" that is used to create data for tests, sometimes generates student names with special characters that make the test fail since the views don't have the correct encoding.

[Image of a test failing with the name "Miss Emerald O'Keefe"](https://i.imgur.com/VlSgcBz.png)

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jljardon.

We have updated the tests and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
