### ISSUE TITLE
I needed to add routes for my tests to pass

### ISSUE THREAD

**Issue by jhharwood88** [learn-co-curriculum/partial-locals-lab#17]
Failures:

  1) Student search when it receives a search query returns all students whose names contain the given string
     Failure/Error: <%= form_tag students_path, method: :get do %>
     
     ActionView::Template::Error:
       undefined local variable or method `students_path' for #<#<Class:0x000055ea769a2b38>:0x000055ea75e86b00>
       Did you mean?  @students
This was also casuing 7 other tests to fail for the exact same reason. 

Once adding routes in for students and classrooms 

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :classrooms
  resources :students
end

It passed all tests.

The lab never specifically mentions needing to create routes, and im not sure if it has other interactions with the previous tests given i was forced to use the solution branch to try to figure out why what looked to be correct code kept failing.

**Comment by helloamandamurphy** [comment]
Bless you for writing this issue. I was writing code and comparing mine with the solution and couldn't figure out what was going on.

**Comment by sgharms** [comment]
Thanks people! Fixed.
