### ISSUE TITLE
Iterating vs. rendering collection

### ISSUE THREAD

**Issue by MaxBrooks114** [learn-co-curriculum/partial-locals-lab#18]
I believe the way the spec is written is a little bottle-necky. The tests only pass if the `@students` variable is iterated through, versus using collections notation i.e. `<%= render partial: "student", collection: @students %>` . Don't they do the same thing?

**Comment by sgharms** [comment]
They do! Tests can be written flexibly or brittle-ly. We've changed the implementation!
