### ISSUE TITLE
Update to Faker Gem

### ISSUE THREAD

**Issue by eponsonby** [learn-co-curriculum/partial-locals-lab#23]
There was an update to the Faker gem that requires the keywords 'from' and 'to" in order for rake db:seed to work. Update the code in the db/seeds.rb file to match the below

`80.times do
  Student.create(name: Faker::Name.name, hometown: Faker::Address.city, birthday: Faker::Date.between(from: 25.years.ago, to: 18.years.ago))
end`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
