### ISSUE TITLE
Missing keywords in seeds.rb

### ISSUE THREAD

**Issue by Lukas-Roberts** [learn-co-curriculum/partial-locals-lab#25]
Missing keywords _**:from**_ and _**:to**_ in the 80.times do block

Currently:

80.times do
  Student.create(name: Faker::Name.name, hometown: Faker::Address.city, birthday: Faker::Date.between(25.years.ago, 18.years.ago))
end

Should be:

80.times do
  Student.create(name: Faker::Name.name, hometown: Faker::Address.city, birthday: Faker::Date.between(**_from:_** 25.years.ago, **_to:_** 18.years.ago))
end

**Comment by drakeltheryuujin** [comment]
Hi there,
Looks like the syntax is currently fixed. Likely happened with our recent deploy of [V8](https://github.com/learn-co-curriculum/partial-locals-lab/blob/dffe5ed36ce01941783a9f573ab8bd27898322ca/db/seeds.rb#L9) of the curriculum.
If you think this issue hasn't been resolved, please re-open this issue. 
Thanks for your feedback!
