### ISSUE TITLE
requires passing in of the f form helper instead of just the instance

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/partial-locals-lab#3]
@blake41 isn't that a weird pattern? I've always just passed in `@student` as a local instead of the `f`

**Comment by blake41** [comment]
if i'm remembering what you're talking about you're referring to students#edit and students#new views where the partial is being rendered inside the form_for block.  i talked to @JeffKatzy about if i remember correctly he was saying that this is a pattern he has run into and wanted to make students aware of it.  but yes i agree i thought it was a weird pattern.  i was thinking of just having the entire form in the partial and passing in the object that the form binds to as a local.

**Comment by pletcher** [comment]
I _think_ this was fixed in 60c29fbc68d8f5c8d118a1069a7d801032d41009, if I'm reading back through the history correctly.
