### ISSUE TITLE
test for search feature too loose

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/partial-locals-lab#5]
you can pass all of the tests without actually building the search feature. if you have partials for _student and render that partial on the student index page, plus `.search` method in Student class, you can pass tests without building  `/students/search` route, `#search` method in students controller, search for on students index page.

**Comment by pletcher** [comment]
I'm waaaay confused by this. The README says to add search functionality for courses and classrooms, but courses don't exist. Only student search is tested for, but as you note, it's incomplete.

Something's fishy here.

**Comment by pletcher** [comment]
Also, I'm super confused by why /students/search would be necessary -- it looks like search is only exposed on the index view.

**Comment by pletcher** [comment]
Fixed in https://github.com/learn-co-curriculum/partial-locals-lab/commit/17467343d4e9b8233af71271f17a9ee15d73db6e
